import {
  KBOTeam,
  KBOGame,
  KBOTeamStanding,
  PitcherLeader,
  BatterLeader,
  HistoricalSeason,
} from '../types/kbo';

export const TEAMS: Record<string, KBOTeam> = {
  LG: { id: 't1', name: 'LG 트윈스', shortName: 'LG', code: 'LG', logoBg: 'bg-rose-950 border-rose-600 text-rose-300' },
  DOOSAN: { id: 't2', name: '두산 베어스', shortName: '두산', code: 'DOOSAN', logoBg: 'bg-sky-950 border-sky-600 text-sky-300' },
  KT: { id: 't3', name: 'KT 위즈', shortName: 'KT', code: 'KT', logoBg: 'bg-zinc-900 border-zinc-500 text-amber-400' },
  SSG: { id: 't4', name: 'SSG 랜더스', shortName: 'SSG', code: 'SSG', logoBg: 'bg-red-950 border-red-600 text-red-300' },
  NC: { id: 't5', name: 'NC 다이노스', shortName: 'NC', code: 'NC', logoBg: 'bg-blue-950 border-cyan-500 text-cyan-300' },
  KIWOOM: { id: 't6', name: '키움 히어로즈', shortName: '키움', code: 'KIWOOM', logoBg: 'bg-fuchsia-950 border-fuchsia-600 text-fuchsia-300' },
  HANWHA: { id: 't7', name: '한화 이글스', shortName: '한화', code: 'HANWHA', logoBg: 'bg-orange-950 border-orange-500 text-orange-300' },
  LOTTE: { id: 't8', name: '롯데 자이언츠', shortName: '롯데', code: 'LOTTE', logoBg: 'bg-indigo-950 border-indigo-500 text-indigo-300' },
  SAMSUNG: { id: 't9', name: '삼성 라이온즈', shortName: '삼성', code: 'SAMSUNG', logoBg: 'bg-blue-950 border-blue-600 text-blue-300' },
  KIA: { id: 't10', name: 'KIA 타이거즈', shortName: 'KIA', code: 'KIA', logoBg: 'bg-red-950 border-rose-600 text-rose-400' },
};

export const MOCK_GAMES: KBOGame[] = [
  {
    id: 'game-20260723-1',
    date: '2026-07-23',
    time: '18:30',
    stadium: '잠실야구장',
    awayTeam: TEAMS.HANWHA,
    homeTeam: TEAMS.LG,
    awayScore: 3,
    homeScore: 4,
    status: 'IN_PROGRESS',
    currentInning: '7회말',
    awayPitcher: '류현진',
    homePitcher: '임찬규',
    broadcast: 'SPOTV',
    aiReview: {
      id: 'ai-r-1',
      gameId: 'game-20260723-1',
      headline: '[실시간 요약] 7회말 터진 역전 적시타, LG 1점 차 리드 잡다',
      summary: '한화 류현진의 6이닝 무실점 호투에도 불구하고 7회말 LG 불펜 공격진의 극적 2점 적시타로 역전에 성공했습니다.',
      keyFactors: [
        '류현진 6이닝 7K 1실점 짠물 투구',
        '7회말 LG 중심타선 집중 3안타 연속타',
        '한화 불펜진의 득점권 주자 허용 급증',
      ],
      pitcherAnalysis: '류현진은 특유의 체인지업으로 타자들을 요리했으나, 7회말 구위 저하 이후 교체 타이밍이 다소 아쉬웠습니다.',
      updatedAt: '2026-07-23 20:45',
    },
    aiPreview: {
      id: 'ai-p-1',
      gameId: 'game-20260723-1',
      headline: '류현진 vs 임찬규, 잠실 빅매치 베테랑 대결',
      summary: '한화의 에이스 류현진과 LG의 안정적인 선발 임찬규의 마운드 대결입니다.',
      keyFactors: [
        '한화 중심 타선의 득점권 타율 상승세',
        'LG 불펜진의 최근 연속 무실점 기록 유지',
      ],
      pitcherAnalysis: '좌완 류현진의 체인지업을 LG 우타진이 어떻게 공략하느냐가 승부처입니다.',
      updatedAt: '2026-07-23 12:00',
    },
  },
  {
    id: 'game-20260723-2',
    date: '2026-07-23',
    time: '18:30',
    stadium: '광주-기아 챔피언스 필드',
    awayTeam: TEAMS.SAMSUNG,
    homeTeam: TEAMS.KIA,
    awayScore: 2,
    homeScore: 7,
    status: 'FINISHED',
    awayPitcher: '원태인',
    homePitcher: '양현종',
    broadcast: 'KBS N SPORTS',
    aiReview: {
      id: 'ai-r-2',
      gameId: 'game-20260723-2',
      headline: '양현종 7이닝 1실점 압도적 호투, KIA 삼성 제압하고 선두 사수',
      summary: 'KIA 양현종이 7이닝 8탈삼진 1실점으로 삼성 타선을 봉쇄하고 시즌 10승을 달성했습니다.',
      keyFactors: [
        '양현종의 QS+ 대호투 및 통산 최다 승수 경신',
        'KIA 나성범 3점 홈런 포함 4타점 폭발',
        '삼성 잔루 9개 득점권 침묵',
      ],
      pitcherAnalysis: '양현종은 직구 최고 147km/h와 슬라이더 조합으로 결정구 삼진 8개를 솎아냈습니다.',
      updatedAt: '2026-07-23 21:30',
    },
  },
  {
    id: 'game-20260723-3',
    date: '2026-07-23',
    time: '18:30',
    stadium: '수원 케이티위즈파크',
    awayTeam: TEAMS.SSG,
    homeTeam: TEAMS.KT,
    awayScore: 8,
    homeScore: 5,
    status: 'FINISHED',
    awayPitcher: '김광현',
    homePitcher: '고영표',
    broadcast: 'MBC SPORTS+',
    aiReview: {
      id: 'ai-r-3',
      gameId: 'game-20260723-3',
      headline: 'SSG 8회초 5득점 대역전극, 김광현 시즌 8승 달성',
      summary: 'SSG가 3-5로 뒤지던 8회초 만루 찬스에서 싹쓸이 2루타를 터뜨리며 역전승을 거두었습니다.',
      keyFactors: [
        '8회초 SSG 타선의 놀라운 득점 집중력',
        '김광현 6이닝 3실점 QS 퀄리티스타트',
      ],
      pitcherAnalysis: '고영표는 체인지업이 살짝 뜨면서 8회 고전을 면치 못했습니다.',
      updatedAt: '2026-07-23 21:50',
    },
  },
  {
    id: 'game-20260723-4',
    date: '2026-07-23',
    time: '18:30',
    stadium: '창원 NC파크',
    awayTeam: TEAMS.DOOSAN,
    homeTeam: TEAMS.NC,
    awayScore: 0,
    homeScore: 0,
    status: 'SCHEDULED',
    awayPitcher: '곽빈',
    homePitcher: '카스타노',
    broadcast: 'SBS SPORTS',
    aiPreview: {
      id: 'ai-p-4',
      gameId: 'game-20260723-4',
      headline: '곽빈 vs 카스타노, 중위권 탈출을 걸어라!',
      summary: '5위 자리를 두고 맞붙는 두산과 NC의 치열한 중위권 분수령전입니다.',
      keyFactors: [
        '곽빈의 최근 3경기 연속 퀄리티스타트 피칭',
        'NC 공룡 타선의 좌타 상대 타율 상승세',
      ],
      pitcherAnalysis: '강속구 투수 곽빈과 제구파 카스타노의 극명한 스타일 대결이 기대됩니다.',
      updatedAt: '2026-07-23 11:30',
    },
  },
];

export const MOCK_STANDINGS_TODAY: KBOTeamStanding[] = [
  { rank: 1, rankChange: 0, team: TEAMS.KIA, gamesPlayed: 90, wins: 55, losses: 33, draws: 2, winRate: 0.625, gameBehind: 0, recent10: '7승 3패', streak: '2연승' },
  { rank: 2, rankChange: 1, team: TEAMS.LG, gamesPlayed: 91, wins: 53, losses: 36, draws: 2, winRate: 0.596, gameBehind: 2.5, recent10: '6승 4패', streak: '1승' },
  { rank: 3, rankChange: -1, team: TEAMS.SAMSUNG, gamesPlayed: 92, wins: 52, losses: 38, draws: 2, winRate: 0.578, gameBehind: 4.0, recent10: '5승 5패', streak: '2연패' },
  { rank: 4, rankChange: 0, team: TEAMS.SSG, gamesPlayed: 89, wins: 48, losses: 40, draws: 1, winRate: 0.545, gameBehind: 7.0, recent10: '8승 2패', streak: '3연승' },
  { rank: 5, rankChange: 1, team: TEAMS.HANWHA, gamesPlayed: 90, wins: 45, losses: 43, draws: 2, winRate: 0.511, gameBehind: 10.0, recent10: '6승 4패', streak: '1패' },
  { rank: 6, rankChange: -1, team: TEAMS.DOOSAN, gamesPlayed: 91, wins: 44, losses: 45, draws: 2, winRate: 0.494, gameBehind: 11.5, recent10: '4승 6패', streak: '1패' },
  { rank: 7, rankChange: 0, team: TEAMS.KT, gamesPlayed: 92, wins: 43, losses: 47, draws: 2, winRate: 0.478, gameBehind: 13.0, recent10: '3승 7패', streak: '3연패' },
  { rank: 8, rankChange: 0, team: TEAMS.NC, gamesPlayed: 89, wins: 40, losses: 47, draws: 2, winRate: 0.460, gameBehind: 14.5, recent10: '5승 5패', streak: '1승' },
  { rank: 9, rankChange: 0, team: TEAMS.LOTTE, gamesPlayed: 88, wins: 38, losses: 48, draws: 2, winRate: 0.442, gameBehind: 16.0, recent10: '4승 6패', streak: '2연패' },
  { rank: 10, rankChange: 0, team: TEAMS.KIWOOM, gamesPlayed: 92, wins: 32, losses: 58, draws: 2, winRate: 0.356, gameBehind: 24.0, recent10: '2승 8패', streak: '5연패' },
];

export const MOCK_PITCHER_LEADERS: PitcherLeader[] = [
  { rank: 1, name: '양현종', team: 'KIA', era: 2.34, wins: 10, losses: 3, saves: 0, strikeouts: 112, whip: 1.05, war: 4.85 },
  { rank: 2, name: '류현진', team: '한화', era: 2.58, wins: 9, losses: 4, saves: 0, strikeouts: 105, whip: 1.10, war: 4.32 },
  { rank: 3, name: '원태인', team: '삼성', era: 2.85, wins: 10, losses: 5, saves: 0, strikeouts: 98, whip: 1.15, war: 3.95 },
  { rank: 4, name: '김광현', team: 'SSG', era: 2.92, wins: 8, losses: 5, saves: 0, strikeouts: 92, whip: 1.18, war: 3.65 },
  { rank: 5, name: '곽빈', team: '두산', era: 3.12, wins: 8, losses: 6, saves: 0, strikeouts: 101, whip: 1.22, war: 3.40 },
];

export const MOCK_BATTER_LEADERS: BatterLeader[] = [
  { rank: 1, name: '김도영', team: 'KIA', avg: 0.348, homeRuns: 28, rbi: 78, ops: 1.042, war: 5.62 },
  { rank: 2, name: '구자욱', team: '삼성', avg: 0.332, homeRuns: 22, rbi: 71, ops: 0.965, war: 4.88 },
  { rank: 3, name: '노시환', team: '한화', avg: 0.315, homeRuns: 25, rbi: 75, ops: 0.942, war: 4.52 },
  { rank: 4, name: '최정', team: 'SSG', avg: 0.298, homeRuns: 24, rbi: 69, ops: 0.925, war: 4.15 },
  { rank: 5, name: '박해민', team: 'LG', avg: 0.312, homeRuns: 8, rbi: 45, ops: 0.845, war: 3.82 },
];

export const MOCK_HISTORICAL_2025: HistoricalSeason = {
  year: 2025,
  champion: 'KIA 타이거즈',
  teams: [
    { rank: 1, name: 'KIA 타이거즈', code: 'KIA', gamesPlayed: 144, wins: 87, losses: 55, draws: 2, winRate: 0.613, postseasonResult: '한국시리즈 우승 🏆' },
    { rank: 2, name: '삼성 라이온즈', code: 'SAMSUNG', gamesPlayed: 144, wins: 78, losses: 64, draws: 2, winRate: 0.549, postseasonResult: '한국시리즈 준우승' },
    { rank: 3, name: 'LG 트윈스', code: 'LG', gamesPlayed: 144, wins: 76, losses: 66, draws: 2, winRate: 0.535, postseasonResult: '플레이오프 탈락' },
    { rank: 4, name: '두산 베어스', code: 'DOOSAN', gamesPlayed: 144, wins: 74, losses: 68, draws: 2, winRate: 0.521, postseasonResult: '준플레이오프 탈락' },
    { rank: 5, name: 'KT 위즈', code: 'KT', gamesPlayed: 144, wins: 72, losses: 70, draws: 2, winRate: 0.507, postseasonResult: '와일드카드 탈락' },
    { rank: 6, name: 'SSG 랜더스', code: 'SSG', gamesPlayed: 144, wins: 72, losses: 70, draws: 2, winRate: 0.507, postseasonResult: '정규 6위' },
    { rank: 7, name: '롯데 자이언츠', code: 'LOTTE', gamesPlayed: 144, wins: 66, losses: 74, draws: 4, winRate: 0.471, postseasonResult: '정규 7위' },
    { rank: 8, name: '한화 이글스', code: 'HANWHA', gamesPlayed: 144, wins: 66, losses: 76, draws: 2, winRate: 0.465, postseasonResult: '정규 8위' },
    { rank: 9, name: 'NC 다이노스', code: 'NC', gamesPlayed: 144, wins: 61, losses: 81, draws: 2, winRate: 0.430, postseasonResult: '정규 9위' },
    { rank: 10, name: '키움 히어로즈', code: 'KIWOOM', gamesPlayed: 144, wins: 58, losses: 86, draws: 0, winRate: 0.403, postseasonResult: '정규 10위' },
  ],
};
